import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.concept': 'Concept',
    'nav.stories': 'Histoires',
    'nav.features': 'Fonctionnalités',
    'nav.creators': 'Créateurs',
    'nav.download': 'Télécharger',

    // Hero
    'hero.greeting': 'Hey, nous sommes',
    'hero.title': 'Plongez dans les mystères de Madagascar',
    'hero.subtitle': 'Découvrez des histoires vraies issues de la culture malgache. Mystère, paranormal, drames — vivez des vécus authentiques en streaming.',
    'hero.problem': 'Les créateurs malgaches n\'avaient pas de maison de production dédiée.',
    'hero.problemDesc': 'Des milliers de talents perdus – créateurs de mystères, traditions, drames réels de Madagascar.',
    'hero.whatIsAppistery': 'MISTERY, c\'est :',
    'hero.feature1': 'Maison de production',
    'hero.feature1Desc': 'd\'histoires vraies',
    'hero.feature2': 'Création de contenu',
    'hero.feature2Desc': 'malgache authentique',
    'hero.feature3': 'Distribution via APPISTERY',
    'hero.feature3Desc': 'la plateforme',
    'hero.conclusion': 'Nous produisons les mystères authentiques de Madagascar.',
    'hero.cta': 'Télécharger l\'application',
    'hero.badge': 'Disponible sur Android',

    // Concept
    'concept.title': 'Le streaming d\'histoires vraies',
    'concept.subtitle': 'APPISTERY réinvente la façon de vivre les vécus authentiques',
    'concept.streaming.title': 'Streaming immersif',
    'concept.streaming.desc': 'Des histoires vraies en streaming, organisées en séries et épisodes pour une expérience de lecture captivante.',
    'concept.culture.title': 'Culture malgache',
    'concept.culture.desc': 'Des vécus issus de la richesse culturelle, sociale et mystique de Madagascar.',
    'concept.series.title': 'Séries & Épisodes',
    'concept.series.desc': 'Chaque histoire est structurée en chapitres pour vous tenir en haleine.',
    'concept.mobile.title': 'Lecture mobile',
    'concept.mobile.desc': 'Une expérience optimisée pour votre smartphone, lisez où que vous soyez.',

    // Featured Stories
    'stories.title': 'Histoires en vedette',
    'stories.subtitle': 'Explorez nos vécus les plus captivants',
    'stories.discover': 'Découvrir',
    'stories.episodes': 'épisodes',
    'stories.series': 'Série',
    'stories.listen': 'Écouter',
    'stories.read': 'Lire',

    // Story titles and descriptions
    'story1.title': 'Les Ombres du Rova',
    'story1.desc': 'Une série de disparitions mystérieuses près du palais royal révèle d\'anciens secrets.',
    'story2.title': 'Le Guérisseur de Toliara',
    'story2.desc': 'Un ombiasy aux pouvoirs troublants aide à résoudre des crimes inexplicables.',
    'story3.title': 'Voix de l\'Au-delà',
    'story3.desc': 'Des témoignages troublants de contacts avec les ancêtres.',
    'story4.title': 'La Malédiction des Vazimba',
    'story4.desc': 'Une famille découvre que leur terre cache un terrible secret.',

    // Genres
    'genre.mystery': 'Mystère',
    'genre.horror': 'Horreur',
    'genre.paranormal': 'Paranormal',
    'genre.drama': 'Drame',
    'genre.witchcraft': 'Sorcellerie',

    // Features
    'features.title': 'Fonctionnalités',
    'features.subtitle': 'Tout ce dont vous avez besoin pour une expérience immersive',
    'features.streaming.title': 'Streaming d\'histoires vraies',
    'features.streaming.desc': 'Accédez à des vécus authentiques basés sur des faits réels de Madagascar.',
    'features.series.title': 'Séries & Chapitres',
    'features.series.desc': 'Des histoires organisées pour une lecture progressive et captivante.',
    'features.theme.title': 'Mode clair / sombre',
    'features.theme.desc': 'Choisissez le thème qui convient à votre moment de lecture.',
    'features.language.title': 'Multilangue FR / EN',
    'features.language.desc': 'Lisez dans la langue de votre choix.',
    'features.favorites.title': 'Favoris',
    'features.favorites.desc': 'Sauvegardez vos histoires préférées pour les retrouver facilement.',
    'features.comments.title': 'Commentaires & Réactions',
    'features.comments.desc': 'Partagez vos impressions avec la communauté.',
    'features.notifications.title': 'Notifications',
    'features.notifications.desc': 'Soyez alerté dès qu\'un nouveau chapitre est disponible.',
    'features.premium.title': 'Abonnement Premium',
    'features.premium.desc': 'Débloquez un accès illimité à tout le contenu.',

    // Access Model
    'access.title': 'Modèle d\'accès',
    'access.subtitle': 'Choisissez la formule qui vous convient',
    'access.free.title': 'Accès Gratuit',
    'access.free.desc': 'Découvrez une sélection d\'histoires gratuitement. Idéal pour explorer la plateforme.',
    'access.free.feature1': 'Histoires gratuites disponibles',
    'access.free.feature2': 'Nouveaux contenus réguliers',
    'access.free.feature3': 'Communauté active',
    'access.premium.title': 'Premium',
    'access.premium.desc': 'Accès illimité à toutes les histoires et fonctionnalités exclusives.',
    'access.premium.feature1': 'Toutes les histoires',
    'access.premium.feature2': 'Sans publicité',
    'access.premium.feature3': 'Chapitres en avant-première',
    'access.premium.feature4': 'Soutien aux créateurs',
    'access.support': 'Soutien aux créateurs',
    'access.support.desc': 'Votre abonnement contribue directement à rémunérer les auteurs.',
    'access.secure': 'Paiement sécurisé',
    'access.secure.desc': 'Transactions protégées et données confidentielles.',
    'access.payment.title': 'Moyens de paiement acceptés',
    'payment.methods.title': 'Moyens de paiement acceptés',

    // Creators
    'creators.title': 'Créateurs de contenu',
    'creators.subtitle': 'La plateforme qui valorise les auteurs malgaches',
    'creators.publish.title': 'Publiez vos histoires',
    'creators.publish.desc': 'Partagez vos vécus avec une audience passionnée par la culture malgache.',
    'creators.earn.title': 'Générez des revenus',
    'creators.earn.desc': 'Chaque lecture de vos histoires vous rapporte. Plus vous êtes lu, plus vous gagnez.',
    'creators.community.title': 'Communauté engagée',
    'creators.community.desc': 'Rejoignez une plateforme équitable et transparente qui met les créateurs au premier plan.',
    'creators.cta': 'Devenir créateur',

    // CTA
    'cta.title': 'Prêt à découvrir les mystères de Madagascar ?',
    'cta.subtitle': 'Téléchargez APPISTERY et plongez dans des histoires vraies qui vous feront frissonner.',
    'cta.button': 'Télécharger Appistery',
    'cta.android': 'Disponible sur Android',

    // Common
    'common.back': 'Retour',
    'common.loading': 'Chargement...',

    // Header
    'header.home': 'Accueil',
    'header.appistery': 'Appistery',
    'header.why': 'Pourquoi',
    'header.login': 'Se Connecter',
    'header.profile': 'Profil',
    'header.logout': 'Déconnexion',

    // Footer
    'footer.description': 'La plateforme de streaming d\'histoires vraies issues de la culture malgache.',
    'footer.description.mistery': 'La plateforme de streaming de histoires malgaches authentiques',
    'footer.navigation': 'Navigation',
    'footer.home': 'Accueil',
    'footer.resources': 'Ressources',
    'footer.about': 'À propos',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.privacy': 'Politique de confidentialité',
    'footer.help': 'Aide',
    'footer.contact': 'Contact',
    'footer.contact.question': 'Avez-vous une question? Contactez-nous',
    'footer.rights': 'Tous les droits réservés',
    'footer.made': 'Fait à Madagascar',
    'footer.madeWith': 'With ❤️ in Madagascar',

    // Privacy Page
    'privacy.title': 'Politique de Confidentialité',
    'privacy.subtitle': 'Votre vie privée est importante pour nous',
    'privacy.introduction': 'Introduction',
    'privacy.introduction.text': 'MISTERY (plateforme de streaming d\'histoires) s\'engage à protéger votre vie privée. Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons vos informations personnelles.',
    'privacy.dataCollection': 'Collecte de Données',
    'privacy.dataCollection.intro': 'Nous collectons les informations suivantes:',
    'privacy.dataCollection.item1': 'Informations d\'identification (nom, email, adresse)',
    'privacy.dataCollection.item2': 'Données de compte (nom d\'utilisateur, mot de passe chiffré)',
    'privacy.dataCollection.item3': 'Informations de paiement (traitées de manière sécurisée)',
    'privacy.dataCollection.item4': 'Données d\'utilisation (pages visitées, historique de lecture)',
    'privacy.dataUsage': 'Utilisation des Données',
    'privacy.dataUsage.intro': 'Nous utilisons vos données pour:',
    'privacy.dataUsage.item1': 'Fournir et améliorer nos services',
    'privacy.dataUsage.item2': 'Gérer votre compte et traiter les paiements',
    'privacy.dataUsage.item3': 'Vous envoyer des mises à jour et notifications',
    'privacy.dataUsage.item4': 'Sécuriser notre plateforme contre les fraudes',
    'privacy.security': 'Sécurité des Données',
    'privacy.security.text': 'Nous utilisons le chiffrement SSL/TLS pour protéger vos données en transit. Vos mots de passe sont chiffrés et jamais stockés en clair. Nous maintenons des mesures de sécurité strictes pour prévenir l\'accès non autorisé.',
    'privacy.rights': 'Vos Droits',
    'privacy.rights.intro': 'Vous avez le droit de:',
    'privacy.rights.item1': 'Accéder à vos données personnelles',
    'privacy.rights.item2': 'Demander la correction de vos données',
    'privacy.rights.item3': 'Demander la suppression de votre compte',
    'privacy.rights.item4': 'Vous retirer de nos communications marketing',
    'privacy.contact': 'Nous Contacter',
    'privacy.contact.intro': 'Pour toute question concernant cette politique de confidentialité, veuillez nous contacter:',
    'privacy.contact.email': 'Email:',
    'privacy.contact.address': 'Adresse: Madagascar',
    'privacy.lastUpdated': 'Dernière mise à jour: janvier 2026',

    // About Page
    'about.title': 'À propos d\'APPISTERY',
    'about.subtitle': 'La plateforme de streaming d\'histoires vraies de Madagascar',
    'about.mission': 'Notre Mission',
    'about.mission.text1': 'MISTERY est né d\'une passion pour les histoires mystérieuses, les témoignages paranormaux et les récits captivants de Madagascar. Notre mission est de donner une voix aux expériences vécues qui frappent l\'imagination et qui incarnent la richesse culturelle et spirituelle de notre île.',
    'about.mission.text2': 'Nous croyons que chaque histoire mérite d\'être entendue. À travers notre plateforme de streaming, nous connectons les conteurs passionnés avec une audience assoiffée de mystère, d\'authenticité et d\'frissons.',
    'about.authenticity': 'Authenticité',
    'about.authenticity.title': 'Histoires Authentiques',
    'about.authenticity.desc': 'Nous valorisons les récits vrais, les expériences vécues et les témoignages sincères. Chaque histoire sur MISTERY est un voyage dans le mystère et l\'insolite.',
    'about.community': 'Communauté',
    'about.community.title': 'Communauté Engagée',
    'about.community.desc': 'Nous construisons une communauté où les conteurs et les auditeurs partagent leur fascination pour les histoires qui défient l\'explication rationnelle.',
    'about.immersive.title': 'Expérience Immersive',
    'about.immersive.desc': 'Notre plateforme offre une expérience audio et vidéo captivante qui vous plonge au cœur de chaque mystère et intrigue.',
    'about.culture': 'Culture Malgache',
    'about.cultural.title': 'Respect Culturel',
    'about.cultural.desc': 'Nous célébrons et préservons le patrimoine cultural malgache en mettant en avant ses histoires les plus captivantes et significatives.',
    'about.whyChoose': 'Pourquoi Choisir MISTERY?',
    'about.exclusive.title': 'Contenu Exclusif',
    'about.exclusive.desc': 'Des histoires que vous ne trouverez nulle part ailleurs, racontées par les créateurs eux-mêmes',
    'about.secure.title': 'Plateforme Sécurisée',
    'about.secure.desc': 'Vos données et votre expérience sont protégées avec nos mesures de sécurité avancées',
    'about.unlimited.title': 'Accès Sans Limites',
    'about.unlimited.desc': 'Écoutez et regardez les histoires quand vous voulez, sur tous vos appareils',
    'about.regular.title': 'Nouveau Contenu Régulier',
    'about.regular.desc': 'Des nouvelles histoires ajoutées chaque semaine pour vous tenir en haleine',
    'about.team.title': 'Notre Équipe',
    'about.team.desc': 'MISTERY est dirigée par une équipe passionnée de Madagascar qui croit au pouvoir des histoires pour divertir, inspirer et rapprocher les gens. Chaque membre de notre équipe apporte sa propre expérience et son amour pour les mystères et les récits captivants.',
    'about.cta.title': 'Prêt à explorer le mystère?',
    'about.cta.desc': 'Rejoignez des milliers de passionnés qui découvrent les histoires les plus captivantes de Madagascar',
    'about.cta.button': 'Retour à l\'Accueil',
    'about.support': 'Soutien aux Créateurs',
    'about.team': 'Rejoignez l\'aventure',

    // Terms Page
    'terms.title': 'Conditions Générales d\'Utilisation',
    'terms.subtitle': 'MISTERY - Plateforme de Streaming d\'Histoires',
    'terms.quickLinks.acceptance': 'Acceptation',
    'terms.quickLinks.acceptance.desc': 'Conditions d\'utilisation',
    'terms.quickLinks.users': 'Utilisateurs',
    'terms.quickLinks.users.desc': 'Droits et obligations',
    'terms.section1.title': '1. Acceptation des Conditions',
    'terms.section1.text1': 'En accédant et en utilisant MISTERY, vous acceptez d\'être lié par ces Conditions Générales d\'Utilisation. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser notre plateforme.',
    'terms.section1.text2': 'MISTERY se réserve le droit de modifier ces conditions à tout moment. Les modifications entrent en vigueur dès leur publication sur la plateforme.',
    'terms.section1.text3': 'Ces conditions s\'appliquent à tous les utilisateurs de MISTERY, y compris les lecteurs, spectateurs et contributeurs.',
    'terms.section2.title': '2. Compte Utilisateur',
    'terms.section2.text1': 'Pour accéder à certaines fonctionnalités, vous devez créer un compte. Vous êtes responsable de :',
    'terms.section2.item1': 'La confidentialité de vos identifiants de connexion',
    'terms.section2.item2': 'Toutes les activités effectuées via votre compte',
    'terms.section2.item3': 'La mise à jour de vos informations personnelles',
    'terms.section2.item4': 'La notification immédiate en cas d\'utilisation non autorisée',
    'terms.section2.text2': 'Vous devez avoir au moins 13 ans pour créer un compte. Les mineurs doivent obtenir le consentement parental.',
    'terms.section3.title': '3. Contenu et Propriété Intellectuelle',
    'terms.section3.subtitle1': '3.1 Contenu sur MISTERY',
    'terms.section3.text1': 'Tout le contenu sur MISTERY (histoires, vidéos, images) est fourni à titre divertissant et informatif. MISTERY s\'engage à respecter les droits d\'auteur et la propriété intellectuelle.',
    'terms.section3.subtitle2': '3.2 Utilisation Personnelle',
    'terms.section3.text2': 'Vous pouvez voir, lire et regarder le contenu à titre personnel. Il est interdit de :',
    'terms.section3.item1': 'Reproduire ou copier le contenu sans autorisation',
    'terms.section3.item2': 'Distribuer ou partager le contenu sur d\'autres plateformes',
    'terms.section3.item3': 'Modifier ou créer des œuvres dérivées',
    'terms.section3.item4': 'Utiliser le contenu à des fins commerciales',
    'terms.section4.title': '4. Conduite des Utilisateurs',
    'terms.section4.text1': 'Vous acceptez de ne pas :',
    'terms.section4.item1': 'Harceler, menacer ou intimider d\'autres utilisateurs',
    'terms.section4.item2': 'Publier du contenu offensant ou discriminatoire',
    'terms.section4.item3': 'Spam ou contenu malveillant',
    'terms.section4.item4': 'Violer les lois applicables',
    'terms.section4.item5': 'Contourner les mesures de sécurité',
    'terms.section4.text2': 'MISTERY se réserve le droit de supprimer tout contenu ou de suspendre les utilisateurs qui violent ces conditions.',
    'terms.section5.title': '5. Abonnement et Paiement',
    'terms.section5.text1': 'MISTERY offre du contenu gratuit et premium. L\'accès au contenu premium nécessite un abonnement payant.',
    'terms.section5.text2': 'Les paiements sont traités de manière sécurisée. Les abonnements se renouvellent automatiquement sauf annulation.',
    'terms.section5.text3': 'Vous pouvez annuler votre abonnement à tout moment. L\'annulation prend effet à la fin de la période en cours.',
    'terms.section6.title': '6. Limitation de Responsabilité',
    'terms.section6.text1': 'MISTERY fournit la plateforme "telle quelle". Nous ne garantissons pas :',
    'terms.section6.item1': 'La disponibilité ininterrompue du service',
    'terms.section6.item2': 'L\'absence d\'erreurs ou de bugs',
    'terms.section6.item3': 'La véracité de certains contenus créatifs',
    'terms.section6.text2': 'MISTERY ne pourra être tenue responsable des dommages directs ou indirects résultant de l\'utilisation de la plateforme.',
    'terms.section7.title': '7. Modification du Service',
    'terms.section7.text': 'MISTERY se réserve le droit de modifier, suspendre ou discontinuer le service à tout moment. Nous notifierons les utilisateurs des changements majeurs.',
    'terms.section8.title': '8. Droit Applicable',
    'terms.section8.text': 'Ces conditions sont régies par les lois de Madagascar. Tout litige sera résolu devant les tribunaux compétents.',
    'terms.contact.title': 'Questions?',
    'terms.contact.text': 'Si vous avez des questions sur ces conditions, veuillez nous contacter :',
    'terms.lastUpdated': 'Dernière mise à jour: janvier 2026',

    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Notre équipe est là pour répondre à vos questions et vous accompagner',

    // Help Page
    'help.title': 'Centre d\'Aide',
    'help.subtitle': 'Trouvez des réponses à vos questions',
    'help.email.title': 'Email',
    'help.email.desc': 'Contactez-nous à contact@mistery.pro',
    'help.support.title': 'Support',
    'help.support.desc': 'Remplissez le formulaire de contact',
    'help.faq.title': 'FAQ',
    'help.faq.desc': 'Consultez nos questions fréquentes',
    'help.faq.section': 'Questions Fréquemment Posées',
    'help.faq.q1': 'Comment puis-je créer un compte?',
    'help.faq.a1': 'Visitez la page d\'inscription et remplissez le formulaire avec vos informations. Vérifiez votre email et vous serez prêt à commencer!',
    'help.faq.q2': 'Comment puis-je me désabonner?',
    'help.faq.a2': 'Accédez à vos paramètres de compte, allez à la section abonnement et cliquez sur \'Annuler l\'abonnement\'.',
    'help.faq.q3': 'Quels sont les modes de paiement acceptés?',
    'help.faq.a3': 'Nous acceptons les cartes de crédit/débit, les portefeuilles mobiles et d\'autres méthodes de paiement locales.',
    'help.faq.q4': 'Comment puis-je signaler un problème?',
    'help.faq.a4': 'Vous pouvez utiliser le formulaire de contact ou nous envoyer un email à contact@mistery.pro avec les détails du problème.',
    'help.faq.q5': 'Ma lecture est-elle synchronisée entre appareils?',
    'help.faq.a5': 'Oui, votre historique de lecture est synchronisé automatiquement sur tous vos appareils connectés.',
    'help.faq.q6': 'Puis-je télécharger des histoires pour lire hors ligne?',
    'help.faq.a6': 'Cette fonctionnalité est actuellement en développement. Elle sera bientôt disponible pour les abonnés.',
    'help.contact.title': 'Vous n\'avez pas trouvé votre réponse?',
    'help.contact.desc': 'Notre équipe de support est là pour vous aider. N\'hésitez pas à nous contacter directement.',
    'help.contact.button': 'Contacter le Support',

    // Creator Space
    'creator.login.title': 'Espace Créateur',
    'creator.login.subtitle': 'Connectez-vous pour gérer vos histoires',
    'creator.login.email': 'Email',
    'creator.login.password': 'Mot de passe',
    'creator.login.show': 'Afficher',
    'creator.login.hide': 'Masquer',
    'creator.login.button': 'Se connecter',
    'creator.login.loading': 'Connexion...',
    'creator.login.noAccount': 'Pas encore de compte ?',
    'creator.login.register': 'S\'inscrire',
    'creator.login.backHome': 'Retour à l\'accueil',
    'creator.login.error': 'Erreur de connexion',

    'creator.register.title': 'Devenir Créateur',
    'creator.register.subtitle': 'Rejoignez notre communauté de créateurs',
    'creator.register.email': 'Email',
    'creator.register.password': 'Mot de passe',
    'creator.register.confirmPassword': 'Confirmer le mot de passe',
    'creator.register.phone': 'Numéro de téléphone',
    'creator.register.biography': 'Biographie',
    'creator.register.biographyPlaceholder': 'Parlez-nous de vous et de votre passion pour l\'écriture...',
    'creator.register.speciality': 'Spécialité',
    'creator.register.specialityPlaceholder': 'Ex: Mystère, Paranormal, Drame...',
    'creator.register.button': 'Créer mon compte',
    'creator.register.loading': 'Inscription...',
    'creator.register.hasAccount': 'Déjà un compte ?',
    'creator.register.login': 'Se connecter',
    'creator.register.backHome': 'Retour à l\'accueil',
    'creator.register.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'creator.register.passwordTooShort': 'Le mot de passe doit contenir au moins 8 caractères',
    'creator.register.error': 'Erreur lors de l\'inscription',

    'creator.dashboard.welcome': 'Bienvenue',
    'creator.dashboard.title': 'Tableau de bord',
    'creator.dashboard.menu.dashboard': 'Tableau de bord',
    'creator.dashboard.menu.stories': 'Mes histoires',
    'creator.dashboard.menu.analytics': 'Statistiques',
    'creator.dashboard.menu.notifications': 'Notifications',
    'creator.dashboard.menu.settings': 'Paramètres',
    'creator.dashboard.logout': 'Déconnexion',
    'creator.dashboard.newStory': 'Nouvelle histoire',

    'creator.dashboard.stats.totalStories': 'Histoires totales',
    'creator.dashboard.stats.totalViews': 'Vues totales',
    'creator.dashboard.stats.totalReactions': 'Réactions',
    'creator.dashboard.stats.followers': 'Abonnés',

    'creator.dashboard.recent.title': 'Histoires récentes',
    'creator.dashboard.recent.empty': 'Aucune histoire pour le moment',
    'creator.dashboard.recent.createFirst': 'Créez votre première histoire pour commencer',
    'creator.dashboard.recent.views': 'vues',
    'creator.dashboard.recent.status.published': 'Publié',
    'creator.dashboard.recent.status.draft': 'Brouillon',

    'creator.dashboard.performance.title': 'Aperçu des performances',
    'creator.dashboard.performance.week': 'Cette semaine',
    'creator.dashboard.performance.month': 'Ce mois',
    'creator.dashboard.performance.growth': 'Croissance',

    'creator.settings.title': 'Paramètres',
    'creator.settings.language': 'Langue',
    'creator.settings.languageDescription': 'Choisissez la langue de l\'interface',
    'creator.settings.theme': 'Thème',
    'creator.settings.themeDescription': 'Gérez l\'apparence de votre espace créateur',
    'creator.settings.theme.light': 'Clair',
    'creator.settings.theme.lightDesc': 'Thème lumineux',
    'creator.settings.theme.dark': 'Sombre',
    'creator.settings.theme.darkDesc': 'Thème sombre',
    'creator.settings.theme.system': 'Système',
    'creator.settings.theme.systemDesc': 'Suit votre système',
    'creator.settings.account': 'Informations du compte',
    'creator.settings.email': 'Email',
    'creator.settings.speciality': 'Spécialité',

    // Mistery Landing
    'mistery.badge': '🎬 Production Malagasy',
    'mistery.title': 'MISTERY',
    'mistery.subtitle': 'Les Meilleures Histoires de Madagascar',
    'mistery.description': 'Une maison de production et distribution dédiée aux histoires authentiques malgaches',
    'mistery.description.full': 'Découvrez des histoires vraies, émouvantes et captivantes issues de la richesse culturelle de Madagascar. Histoires de mystère, paranormal, drames authentiques et traditions malgaches.',
    'mistery.watch': 'Télécharger l\'application',
    'mistery.signin': 'Se connecter',
    'mistery.stories': '50+',
    'mistery.stories.label': 'Histoires',
    'mistery.creators': '1000+',
    'mistery.creators.label': 'Créateurs',
    'mistery.viewers': '166K+',
    'mistery.viewers.label': 'Abonnés',
    'mistery.featured': 'À regarder maintenant',
    'mistery.featured.desc': 'Découvrez les histoires les plus regardées cette semaine',
    'mistery.explore': 'Explorer plus',
    'mistery.about.title': 'Qu\'est-ce que MISTERY?',
    'mistery.authentic': 'Histoires Authentiques',
    'mistery.authentic.desc': 'Des histoires vraies, émouvantes et captivantes de Madagascar',
    'mistery.culture': 'Culture Malgache',
    'mistery.culture.desc': 'Célèbre et préserve la richesse culturelle à travers les histoires',
    'mistery.authors': 'Auteurs Malgaches',
    'mistery.authors.desc': 'Soutien aux talents locaux et à la littérature malgache',
    'mistery.quality': 'Qualité Premium',
    'mistery.quality.desc': 'Accès illimité à des centaines d\'histoires de qualité supérieure',
    'mistery.safe': 'Contenu Sécurisé',
    'mistery.safe.desc': 'Plateforme fiable avec du contenu vérifié et de qualité',
    'mistery.anytime': 'À Votre Rythme',
    'mistery.anytime.desc': 'Regardez quand vous voulez, où vous voulez, sur tous vos appareils',
    'mistery.why': 'Pourquoi MISTERY?',
    'mistery.why.content': 'Meilleur Contenu',
    'mistery.why.content.desc': 'Les meilleures histoires malgaches en un seul endroit',
    'mistery.why.everywhere': 'Partout, Toujours',
    'mistery.why.everywhere.desc': 'Regardez sur votre téléphone, tablette ou ordinateur',
    'mistery.why.support': 'Soutenu l\'Art Local',
    'mistery.why.support.desc': 'Chaque visionnage soutient les auteurs malgaches',
    'mistery.discover': 'Découvrez des Histoires Uniques',
    'mistery.discover.desc': 'Immergez-vous dans les histoires authentiques de Madagascar',
    'mistery.now': 'Commencer maintenant',
    'mistery.why.title': 'Pourquoi ?',
    'mistery.why.question': 'Pourquoi créer une maison de production dédiée aux histoires malgaches ?',
    'mistery.why.answer1': 'Parce que Madagascar regorge de mystères, de traditions ancestrales et d\'histoires vraies qui méritent d\'être racontées de manière authentique et professionnelle.',
    'mistery.why.answer2': 'MISTERY donne aux créateurs malgaches les outils, le soutien et la plateforme pour transformer leurs histoires en contenus vidéo captivants distribués via APPISTERY.',
  },
  en: {
    // Navigation
    'nav.concept': 'Concept',
    'nav.stories': 'Stories',
    'nav.features': 'Features',
    'nav.creators': 'Creators',
    'nav.download': 'Download',

    // Hero
    'hero.greeting': 'Hey, we are',
    'hero.title': 'Dive into the mysteries of Madagascar',
    'hero.subtitle': 'Discover true stories from Malagasy culture. Mystery, paranormal, drama — experience authentic tales in streaming.',
    'hero.problem': 'Malagasy creators had no dedicated production house.',
    'hero.problemDesc': 'Thousands of lost talents – creators of mysteries, traditions, real dramas from Madagascar.',
    'hero.whatIsAppistery': 'MISTERY is:',
    'hero.feature1': 'Production house',
    'hero.feature1Desc': 'for true stories',
    'hero.feature2': 'Creation of content',
    'hero.feature2Desc': 'authentic Malagasy',
    'hero.feature3': 'Distribution via APPISTERY',
    'hero.feature3Desc': 'the platform',
    'hero.conclusion': 'We produce the authentic mysteries of Madagascar.',
    'hero.cta': 'Download the app',
    'hero.badge': 'Available on Android',

    // Concept
    'concept.title': 'True story streaming',
    'concept.subtitle': 'APPISTERY reinvents how you experience authentic tales',
    'concept.streaming.title': 'Immersive streaming',
    'concept.streaming.desc': 'True stories in streaming, organized in series and episodes for a captivating reading experience.',
    'concept.culture.title': 'Malagasy culture',
    'concept.culture.desc': 'Tales from the cultural, social and mystical richness of Madagascar.',
    'concept.series.title': 'Series & Episodes',
    'concept.series.desc': 'Each story is structured in chapters to keep you on the edge.',
    'concept.mobile.title': 'Mobile reading',
    'concept.mobile.desc': 'An optimized experience for your smartphone, read wherever you are.',

    // Featured Stories
    'stories.title': 'Featured Stories',
    'stories.subtitle': 'Explore our most captivating tales',
    'stories.discover': 'Discover',
    'stories.episodes': 'episodes',
    'stories.series': 'Series',
    'stories.listen': 'Listen',
    'stories.read': 'Read',

    // Story titles and descriptions
    'story1.title': 'Shadows of the Rova',
    'story1.desc': 'A series of mysterious disappearances near the royal palace reveals ancient secrets.',
    'story2.title': 'The Healer of Toliara',
    'story2.desc': 'An ombiasy with disturbing powers helps solve inexplicable crimes.',
    'story3.title': 'Voices from Beyond',
    'story3.desc': 'Disturbing testimonies of contact with the ancestors.',
    'story4.title': 'The Vazimba Curse',
    'story4.desc': 'A family discovers their land hides a terrible secret.',

    // Genres
    'genre.mystery': 'Mystery',
    'genre.horror': 'Horror',
    'genre.paranormal': 'Paranormal',
    'genre.drama': 'Drama',
    'genre.witchcraft': 'Witchcraft',

    // Features
    'features.title': 'Features',
    'features.subtitle': 'Everything you need for an immersive experience',
    'features.streaming.title': 'True story streaming',
    'features.streaming.desc': 'Access authentic tales based on real events from Madagascar.',
    'features.series.title': 'Series & Chapters',
    'features.series.desc': 'Stories organized for progressive and captivating reading.',
    'features.theme.title': 'Light / Dark mode',
    'features.theme.desc': 'Choose the theme that suits your reading moment.',
    'features.language.title': 'Multilingual FR / EN',
    'features.language.desc': 'Read in the language of your choice.',
    'features.favorites.title': 'Favorites',
    'features.favorites.desc': 'Save your favorite stories for easy access.',
    'features.comments.title': 'Comments & Reactions',
    'features.comments.desc': 'Share your impressions with the community.',
    'features.notifications.title': 'Notifications',
    'features.notifications.desc': 'Get notified when a new chapter is available.',
    'features.premium.title': 'Premium Subscription',
    'features.premium.desc': 'Unlock unlimited access to all content.',

    // Access Model
    'access.title': 'Access Model',
    'access.subtitle': 'Choose the plan that suits you',
    'access.free.title': 'Free Access',
    'access.free.desc': 'Discover a selection of free stories. Perfect for exploring the platform.',
    'access.free.feature1': 'Free stories available',
    'access.free.feature2': 'Regular new content',
    'access.free.feature3': 'Active community',
    'access.premium.title': 'Premium',
    'access.premium.desc': 'Unlimited access to all stories and exclusive features.',
    'access.premium.feature1': 'All stories',
    'access.premium.feature2': 'Ad-free',
    'access.premium.feature3': 'Early access chapters',
    'access.premium.feature4': 'Support creators',
    'access.support': 'Support creators',
    'access.support.desc': 'Your subscription directly helps compensate authors.',
    'access.secure': 'Secure payment',
    'access.secure.desc': 'Protected transactions and confidential data.',
    'access.payment.title': 'Accepted payment methods',
    'payment.methods.title': 'Accepted payment methods',

    // Creators
    'creators.title': 'Content Creators',
    'creators.subtitle': 'The platform that values Malagasy authors',
    'creators.publish.title': 'Publish your stories',
    'creators.publish.desc': 'Share your tales with an audience passionate about Malagasy culture.',
    'creators.earn.title': 'Generate revenue',
    'creators.earn.desc': 'Every read of your stories earns you money. The more you\'re read, the more you earn.',
    'creators.community.title': 'Engaged community',
    'creators.community.desc': 'Join a fair and transparent platform that puts creators first.',
    'creators.cta': 'Become a creator',

    // CTA
    'cta.title': 'Ready to discover the mysteries of Madagascar?',
    'cta.subtitle': 'Download APPISTERY and dive into true stories that will thrill you.',
    'cta.button': 'Download Appistery',
    'cta.android': 'Available on Android',

    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',

    // Header
    'header.home': 'Home',
    'header.appistery': 'Appistery',
    'header.why': 'Why',
    'header.login': 'Login',
    'header.profile': 'Profile',
    'header.logout': 'Logout',

    // Footer
    'footer.description': 'The streaming platform for true stories from Malagasy culture.',
    'footer.description.mistery': 'The streaming platform for authentic Malagasy stories',
    'footer.navigation': 'Navigation',
    'footer.home': 'Home',
    'footer.resources': 'Resources',
    'footer.about': 'About',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.contact.question': 'Have a question? Contact us',
    'footer.rights': 'All rights reserved',
    'footer.made': 'Made in Madagascar',
    'footer.madeWith': 'With ❤️ in Madagascar',

    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Your privacy matters to us',
    'privacy.introduction': 'Introduction',
    'privacy.introduction.text': 'MISTERY (story streaming platform) is committed to protecting your privacy. This privacy policy explains how we collect, use and protect your personal information.',
    'privacy.dataCollection': 'Data Collection',
    'privacy.dataCollection.intro': 'We collect the following information:',
    'privacy.dataCollection.item1': 'Identification information (name, email, address)',
    'privacy.dataCollection.item2': 'Account data (username, encrypted password)',
    'privacy.dataCollection.item3': 'Payment information (securely processed)',
    'privacy.dataCollection.item4': 'Usage data (pages visited, reading history)',
    'privacy.dataUsage': 'Data Usage',
    'privacy.dataUsage.intro': 'We use your data to:',
    'privacy.dataUsage.item1': 'Provide and improve our services',
    'privacy.dataUsage.item2': 'Manage your account and process payments',
    'privacy.dataUsage.item3': 'Send you updates and notifications',
    'privacy.dataUsage.item4': 'Secure our platform against fraud',
    'privacy.security': 'Data Security',
    'privacy.security.text': 'We use SSL/TLS encryption to protect your data in transit. Your passwords are encrypted and never stored in plain text. We maintain strict security measures to prevent unauthorized access.',
    'privacy.rights': 'Your Rights',
    'privacy.rights.intro': 'You have the right to:',
    'privacy.rights.item1': 'Access your personal data',
    'privacy.rights.item2': 'Request correction of your data',
    'privacy.rights.item3': 'Request deletion of your account',
    'privacy.rights.item4': 'Opt out of marketing communications',
    'privacy.contact': 'Contact Us',
    'privacy.contact.intro': 'For any questions regarding this privacy policy, please contact us:',
    'privacy.contact.email': 'Email:',
    'privacy.contact.address': 'Address: Madagascar',
    'privacy.lastUpdated': 'Last updated: January 2026',

    // About Page
    'about.title': 'About APPISTERY',
    'about.subtitle': 'The streaming platform for true stories from Madagascar',
    'about.mission': 'Our Mission',
    'about.mission.text1': 'MISTERY was born from a passion for mysterious stories, paranormal testimonies and captivating narratives from Madagascar. Our mission is to give a voice to lived experiences that capture the imagination and embody the cultural and spiritual richness of our island.',
    'about.mission.text2': 'We believe every story deserves to be heard. Through our streaming platform, we connect passionate storytellers with an audience hungry for mystery, authenticity and thrills.',
    'about.authenticity': 'Authenticity',
    'about.authenticity.title': 'Authentic Stories',
    'about.authenticity.desc': 'We value true narratives, lived experiences and sincere testimonies. Each story on MISTERY is a journey into mystery and the unusual.',
    'about.community': 'Community',
    'about.community.title': 'Engaged Community',
    'about.community.desc': 'We build a community where storytellers and listeners share their fascination for stories that defy rational explanation.',
    'about.immersive.title': 'Immersive Experience',
    'about.immersive.desc': 'Our platform offers a captivating audio and video experience that immerses you in the heart of each mystery and intrigue.',
    'about.culture': 'Malagasy Culture',
    'about.cultural.title': 'Cultural Respect',
    'about.cultural.desc': 'We celebrate and preserve Malagasy cultural heritage by highlighting its most captivating and meaningful stories.',
    'about.whyChoose': 'Why Choose MISTERY?',
    'about.exclusive.title': 'Exclusive Content',
    'about.exclusive.desc': 'Stories you won\'t find anywhere else, told by the creators themselves',
    'about.secure.title': 'Secure Platform',
    'about.secure.desc': 'Your data and experience are protected with our advanced security measures',
    'about.unlimited.title': 'Unlimited Access',
    'about.unlimited.desc': 'Listen and watch stories whenever you want, on all your devices',
    'about.regular.title': 'Regular New Content',
    'about.regular.desc': 'New stories added every week to keep you on the edge',
    'about.team.title': 'Our Team',
    'about.team.desc': 'MISTERY is led by a passionate team from Madagascar who believe in the power of stories to entertain, inspire and bring people together. Each member of our team brings their own experience and love for mysteries and captivating narratives.',
    'about.cta.title': 'Ready to explore the mystery?',
    'about.cta.desc': 'Join thousands of enthusiasts discovering the most captivating stories from Madagascar',
    'about.cta.button': 'Back to Home',
    'about.support': 'Support for Creators',
    'about.team': 'Join the adventure',

    // Terms Page
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'MISTERY - Story Streaming Platform',
    'terms.quickLinks.acceptance': 'Acceptance',
    'terms.quickLinks.acceptance.desc': 'Terms of use',
    'terms.quickLinks.users': 'Users',
    'terms.quickLinks.users.desc': 'Rights and obligations',
    'terms.section1.title': '1. Acceptance of Terms',
    'terms.section1.text1': 'By accessing and using MISTERY, you agree to be bound by these Terms of Service. If you do not accept these terms, please do not use our platform.',
    'terms.section1.text2': 'MISTERY reserves the right to modify these terms at any time. Changes become effective as soon as they are published on the platform.',
    'terms.section1.text3': 'These terms apply to all MISTERY users, including readers, viewers and contributors.',
    'terms.section2.title': '2. User Account',
    'terms.section2.text1': 'To access certain features, you must create an account. You are responsible for:',
    'terms.section2.item1': 'The confidentiality of your login credentials',
    'terms.section2.item2': 'All activities performed through your account',
    'terms.section2.item3': 'Updating your personal information',
    'terms.section2.item4': 'Immediate notification in case of unauthorized use',
    'terms.section2.text2': 'You must be at least 13 years old to create an account. Minors must obtain parental consent.',
    'terms.section3.title': '3. Content and Intellectual Property',
    'terms.section3.subtitle1': '3.1 Content on MISTERY',
    'terms.section3.text1': 'All content on MISTERY (stories, videos, images) is provided for entertainment and informational purposes. MISTERY is committed to respecting copyright and intellectual property.',
    'terms.section3.subtitle2': '3.2 Personal Use',
    'terms.section3.text2': 'You may view, read and watch content for personal use. It is prohibited to:',
    'terms.section3.item1': 'Reproduce or copy content without authorization',
    'terms.section3.item2': 'Distribute or share content on other platforms',
    'terms.section3.item3': 'Modify or create derivative works',
    'terms.section3.item4': 'Use content for commercial purposes',
    'terms.section4.title': '4. User Conduct',
    'terms.section4.text1': 'You agree not to:',
    'terms.section4.item1': 'Harass, threaten or intimidate other users',
    'terms.section4.item2': 'Post offensive or discriminatory content',
    'terms.section4.item3': 'Spam or malicious content',
    'terms.section4.item4': 'Violate applicable laws',
    'terms.section4.item5': 'Bypass security measures',
    'terms.section4.text2': 'MISTERY reserves the right to remove any content or suspend users who violate these terms.',
    'terms.section5.title': '5. Subscription and Payment',
    'terms.section5.text1': 'MISTERY offers free and premium content. Access to premium content requires a paid subscription.',
    'terms.section5.text2': 'Payments are processed securely. Subscriptions renew automatically unless cancelled.',
    'terms.section5.text3': 'You can cancel your subscription at any time. Cancellation takes effect at the end of the current period.',
    'terms.section6.title': '6. Limitation of Liability',
    'terms.section6.text1': 'MISTERY provides the platform "as is". We do not guarantee:',
    'terms.section6.item1': 'Uninterrupted service availability',
    'terms.section6.item2': 'The absence of errors or bugs',
    'terms.section6.item3': 'The veracity of certain creative content',
    'terms.section6.text2': 'MISTERY cannot be held liable for direct or indirect damages resulting from use of the platform.',
    'terms.section7.title': '7. Service Modification',
    'terms.section7.text': 'MISTERY reserves the right to modify, suspend or discontinue the service at any time. We will notify users of major changes.',
    'terms.section8.title': '8. Applicable Law',
    'terms.section8.text': 'These terms are governed by the laws of Madagascar. Any dispute will be resolved before the competent courts.',
    'terms.contact.title': 'Questions?',
    'terms.contact.text': 'If you have questions about these terms, please contact us:',
    'terms.lastUpdated': 'Last updated: January 2026',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Our team is here to answer your questions and support you',

    // Help Page
    'help.title': 'Help Center',
    'help.subtitle': 'Find answers to your questions',
    'help.email.title': 'Email',
    'help.email.desc': 'Contact us at contact@mistery.pro',
    'help.support.title': 'Support',
    'help.support.desc': 'Fill out the contact form',
    'help.faq.title': 'FAQ',
    'help.faq.desc': 'Check our frequently asked questions',
    'help.faq.section': 'Frequently Asked Questions',
    'help.faq.q1': 'How can I create an account?',
    'help.faq.a1': 'Visit the registration page and fill out the form with your information. Verify your email and you\'ll be ready to start!',
    'help.faq.q2': 'How can I unsubscribe?',
    'help.faq.a2': 'Go to your account settings, navigate to the subscription section and click \'Cancel subscription\'.',
    'help.faq.q3': 'What payment methods are accepted?',
    'help.faq.a3': 'We accept credit/debit cards, mobile wallets and other local payment methods.',
    'help.faq.q4': 'How can I report a problem?',
    'help.faq.a4': 'You can use the contact form or send us an email at contact@mistery.pro with the details of the problem.',
    'help.faq.q5': 'Is my reading synced between devices?',
    'help.faq.a5': 'Yes, your reading history is automatically synced across all your connected devices.',
    'help.faq.q6': 'Can I download stories to read offline?',
    'help.faq.a6': 'This feature is currently in development. It will soon be available for subscribers.',
    'help.contact.title': 'Didn\'t find your answer?',
    'help.contact.desc': 'Our support team is here to help. Don\'t hesitate to contact us directly.',
    'help.contact.button': 'Contact Support',

    // Creator Space
    'creator.login.title': 'Creator Space',
    'creator.login.subtitle': 'Log in to manage your stories',
    'creator.login.email': 'Email',
    'creator.login.password': 'Password',
    'creator.login.show': 'Show',
    'creator.login.hide': 'Hide',
    'creator.login.button': 'Log in',
    'creator.login.loading': 'Logging in...',
    'creator.login.noAccount': 'Don\'t have an account?',
    'creator.login.register': 'Sign up',
    'creator.login.backHome': 'Back to home',
    'creator.login.error': 'Login error',

    'creator.register.title': 'Become a Creator',
    'creator.register.subtitle': 'Join our community of creators',
    'creator.register.email': 'Email',
    'creator.register.password': 'Password',
    'creator.register.confirmPassword': 'Confirm password',
    'creator.register.phone': 'Phone number',
    'creator.register.biography': 'Biography',
    'creator.register.biographyPlaceholder': 'Tell us about yourself and your passion for writing...',
    'creator.register.speciality': 'Speciality',
    'creator.register.specialityPlaceholder': 'E.g: Mystery, Paranormal, Drama...',
    'creator.register.button': 'Create my account',
    'creator.register.loading': 'Signing up...',
    'creator.register.hasAccount': 'Already have an account?',
    'creator.register.login': 'Log in',
    'creator.register.backHome': 'Back to home',
    'creator.register.passwordMismatch': 'Passwords do not match',
    'creator.register.passwordTooShort': 'Password must be at least 8 characters',
    'creator.register.error': 'Registration error',

    'creator.dashboard.welcome': 'Welcome',
    'creator.dashboard.title': 'Dashboard',
    'creator.dashboard.menu.dashboard': 'Dashboard',
    'creator.dashboard.menu.stories': 'My stories',
    'creator.dashboard.menu.analytics': 'Analytics',
    'creator.dashboard.menu.notifications': 'Notifications',
    'creator.dashboard.menu.settings': 'Settings',
    'creator.dashboard.logout': 'Logout',
    'creator.dashboard.newStory': 'New story',

    'creator.dashboard.stats.totalStories': 'Total stories',
    'creator.dashboard.stats.totalViews': 'Total views',
    'creator.dashboard.stats.totalReactions': 'Reactions',
    'creator.dashboard.stats.followers': 'Followers',

    'creator.dashboard.recent.title': 'Recent stories',
    'creator.dashboard.recent.empty': 'No stories yet',
    'creator.dashboard.recent.createFirst': 'Create your first story to get started',
    'creator.dashboard.recent.views': 'views',
    'creator.dashboard.recent.status.published': 'Published',
    'creator.dashboard.recent.status.draft': 'Draft',

    'creator.dashboard.performance.title': 'Performance overview',
    'creator.dashboard.performance.week': 'This week',
    'creator.dashboard.performance.month': 'This month',
    'creator.dashboard.performance.growth': 'Growth',

    'creator.settings.title': 'Settings',
    'creator.settings.language': 'Language',
    'creator.settings.languageDescription': 'Choose your interface language',
    'creator.settings.theme': 'Theme',
    'creator.settings.themeDescription': 'Manage your creator space appearance',
    'creator.settings.theme.light': 'Light',
    'creator.settings.theme.lightDesc': 'Light theme',
    'creator.settings.theme.dark': 'Dark',
    'creator.settings.theme.darkDesc': 'Dark theme',
    'creator.settings.theme.system': 'System',
    'creator.settings.theme.systemDesc': 'Follow your system',
    'creator.settings.account': 'Account information',
    'creator.settings.email': 'Email',
    'creator.settings.speciality': 'Speciality',

    // Mistery Landing
    'mistery.badge': '🎬 Malagasy Production',
    'mistery.title': 'MISTERY',
    'mistery.subtitle': 'The Best Stories from Madagascar',
    'mistery.description': 'A production and distribution company dedicated to authentic Malagasy stories',
    'mistery.description.full': 'Discover true, moving and captivating stories from the cultural richness of Madagascar. Mystery stories, paranormal, authentic dramas and Malagasy traditions.',
    'mistery.watch': 'Download the app',
    'mistery.signin': 'Sign in',
    'mistery.stories': '50+',
    'mistery.stories.label': 'Stories',
    'mistery.creators': '1000+',
    'mistery.creators.label': 'Creators',
    'mistery.viewers': '166K+',
    'mistery.viewers.label': 'Followers',
    'mistery.featured': 'Watch now',
    'mistery.featured.desc': 'Discover the most watched stories this week',
    'mistery.explore': 'Explore more',
    'mistery.about.title': 'What is MISTERY?',
    'mistery.authentic': 'Authentic Stories',
    'mistery.authentic.desc': 'True, moving and captivating stories from Madagascar',
    'mistery.culture': 'Malagasy Culture',
    'mistery.culture.desc': 'Celebrates and preserves cultural wealth through stories',
    'mistery.authors': 'Malagasy Authors',
    'mistery.authors.desc': 'Support for local talents and Malagasy literature',
    'mistery.quality': 'Premium Quality',
    'mistery.quality.desc': 'Unlimited access to hundreds of high quality stories',
    'mistery.safe': 'Safe Content',
    'mistery.safe.desc': 'Reliable platform with verified and quality content',
    'mistery.anytime': 'On Your Schedule',
    'mistery.anytime.desc': 'Watch when you want, where you want, on all your devices',
    'mistery.why': 'Why MISTERY?',
    'mistery.why.content': 'Best Content',
    'mistery.why.content.desc': 'The best Malagasy stories in one place',
    'mistery.why.everywhere': 'Everywhere, Always',
    'mistery.why.everywhere.desc': 'Watch on your phone, tablet or computer',
    'mistery.why.support': 'Support Local Art',
    'mistery.why.support.desc': 'Every view supports Malagasy authors',
    'mistery.discover': 'Discover Unique Stories',
    'mistery.discover.desc': 'Immerse yourself in authentic stories from Madagascar',
    'mistery.now': 'Start now',
    'mistery.why.title': 'Why ??',
    'mistery.why.question': 'Why create a production house dedicated to Malagasy stories?',
    'mistery.why.answer1': 'Because Madagascar is full of mysteries, ancestral traditions and true stories that deserve to be told authentically and professionally.',
    'mistery.why.answer2': 'MISTERY gives Malagasy creators the tools, support and platform to transform their stories into captivating video content distributed via APPISTERY.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('appistery-language');
      if (saved === 'fr' || saved === 'en') return saved;
      const browserLang = navigator.language.toLowerCase();
      return browserLang.startsWith('fr') ? 'fr' : 'en';
    }
    return 'fr';
  });

  useEffect(() => {
    localStorage.setItem('appistery-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
